Fix crash in custom django-celery-beat scheduler entries (#11071)
This fixes `django-celery-beat` startup crashes when using custom database scheduler. This crash would happen when trying to load `django-celery-beat` rows from database due to a breaking change introduced at https://github.com/celery/django-celery-beat/commit/626c2a06331a039250ea4026812bf1ede26907cc#diff-30f45e7eed4aafe79dbc3b004881b237faf4393938b769fff25325364384bced (`django-celery-beat==2.4.0`).

Stacktrace:
```
AttributeError: tuple object has no attribute name
  File "django_celery_beat/schedulers.py", line 315, in update_from_dict
    entry = self.Entry.from_entry(name,
  File "saleor/schedulers/schedulers.py", line 53, in from_entry
    return cls(
  File "django_celery_beat/schedulers.py", line 50, in __init__
    self.name = model.name
```

Issue was introduced by https://github.com/saleor/saleor/commit/1f145853f9856ac5c92b65afd35873e4198af31d