fix: crash when telemetry is disabled and lifespan is enabled (#19207)
When `SEND_USAGE_TELEMETRY=False` and `--lifespan=on` was still present, the startup would crash:

```
$ SEND_USAGE_TELEMETRY=false uvicorn saleor.asgi:application --lifespan=on
2026-05-14 15:16:09,412 WARNING saleor.core.jwt_manager RSA_PRIVATE_KEY is missing. Using temporary key for local development with DEBUG mode. [PID:45018:MainThread]
INFO:     Started server process [45018]
INFO:     Waiting for application startup.
ERROR:    Exception in 'lifespan' protocol
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/uvicorn/lifespan/on.py", line 86, in main
    await app(scope, self.receive, self.send)
  File "/usr/local/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 29, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/saleor/asgi/telemetry.py", line 26, in telemetry_wrapper
    return await application(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/saleor/asgi/cors_handler.py", line 21, in cors_wrapper
    await application(scope, receive, send)
  File "/app/saleor/asgi/gzip_compression.py", line 145, in gzip_compression_wrapper
    await app(scope, receive, send)
  File "/app/saleor/asgi/health_check.py", line 16, in health_check_wrapper
    return await application(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/asgi.py", line 161, in __call__
    raise ValueError(
ValueError: Django can only handle ASGI/HTTP connections, not lifespan.
ERROR:    Application startup failed. Exiting.
```

This issue is resolved by leaving it up to uvicorn to detect whether to enable lifespan or disable it.