fix: celery loggers being used outside Celery (#16334)
Cherry-pick of e91211de0254617d7467a3683bdeeeceecb890fc.

---

This fixes an issue where Celery loggers were used outside Celery thus leading to background crash in the Python logging logic.

Example bad pattern:

```python
import logging
from celery.utils.log import get_task_logger

logger = logging.getLogger(__name__)

task_logger = get_task_logger(__name__)

def handle_POST_graphql():
   logger.info("Received GraphQL Request")  # Leads to a background crash
```

This is leads to such crashes outside Celery:

```
File "/app/saleor/core/logging.py", line 41, in add_fields
"celeryTaskId": task.request.id,
AttributeError: 'NoneType' object has no attribute 'request'
```

This also causes any custom logging attributes or formatting to be lost (e.g., adding the URL to each HTTP log entry)

The issue was fixed by renaming all task loggers in order to no longer clash with non-task loggers.