Fix mypy errors in GraphQL common types
`mypy` was throwing errors at `saleor/graphql/core/types/common.py` about unused type-ignores:

```

saleor/graphql/core/types/common.py:179: error: Unused "type: ignore" comment 
[unused-ignore]
        address_type = AddressTypeEnum(  # type: ignore[has-type]
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
saleor/graphql/core/types/common.py:264: error: Unused "type: ignore" comment 
[unused-ignore]
        address_type = AddressTypeEnum(  # type: ignore[has-type]
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
saleor/graphql/core/types/common.py:352: error: Unused "type: ignore" comment 
[unused-ignore]
        address_type = AddressTypeEnum(  # type: ignore[has-type]
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Found 4 errors in 2 files (checked 16 source files)
```