fix(populatedb): crash when creating orders
0d2fff570f2a3e8d616b757c3d7d43bca6245fd5 (#17783) improperly updated `random_data.py`, which thus causes the following crash:

```
Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/psycopg/cursor.py", line 97, in execute
    raise ex.with_traceback(None)
psycopg.errors.NotNullViolation: null value in column "lines_count" of relation "order_order" violates not-null constraint
DETAIL:  Failing row contains (2026-07-17 11:54:31.660873+00, , jason.garcia@example.com, 46a548dc-2dc3-4255-914b-11111c6daad8, 806, 806, null, 0.000, null, en, 71.780, 0.000, 71.780, unfulfilled, FedEx Express, 216, t, , 0, , USD, {}, {}, 1, null, null, 0.000, 0.000, 0.000, , null, null, , 2026-07-17 11:54:31.661162+00, f, 211, null, 0.000, none, none, null, t, f, 71.780, null, {}, null, {}, null, null, null, 0.000, 0.000, null, 71.780, null, null, null, {}, {}).

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/app/.venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/app/.venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/app/.venv/lib/python3.12/site-packages/django/core/management/base.py", line 420, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/app/.venv/lib/python3.12/site-packages/django/core/management/base.py", line 464, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/saleor/core/management/commands/populatedb.py", line 112, in handle
    for msg in create_orders(20):
               ^^^^^^^^^^^^^^^^^
  File "/app/saleor/core/utils/random_data.py", line 1019, in create_orders
    order = create_fake_order()
            ^^^^^^^^^^^^^^^^^^^
  File "/app/saleor/core/utils/random_data.py", line 814, in create_fake_order
    order = Order.objects.create(**order_data)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 665, in create
    obj.save(force_insert=True, using=self.db)
  File "/app/.venv/lib/python3.12/site-packages/django/db/models/base.py", line 902, in save
    self.save_base(
  File "/app/.venv/lib/python3.12/site-packages/django/db/models/base.py", line 1008, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/django/db/models/base.py", line 1169, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/django/db/models/base.py", line 1210, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 1873, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1882, in execute_sql
    cursor.execute(sql, params)
  File "/app/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/app/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/psycopg/cursor.py", line 97, in execute
    raise ex.with_traceback(None)
django.db.utils.IntegrityError: null value in column "lines_count" of relation "order_order" violates not-null constraint
DETAIL:  Failing row contains (2026-07-17 11:54:31.660873+00, , jason.garcia@example.com, 46a548dc-2dc3-4255-914b-11111c6daad8, 806, 806, null, 0.000, null, en, 71.780, 0.000, 71.780, unfulfilled, FedEx Express, 216, t, , 0, , USD, {}, {}, 1, null, null, 0.000, 0.000, 0.000, , null, null, , 2026-07-17 11:54:31.661162+00, f, 211, null, 0.000, none, none, null, t, f, 71.780, null, {}, null, {}, null, null, null, 0.000, 0.000, null, 71.780, null, null, null, {}, {}).
```

In 3.22+ this is not the case because it's properly set to `0` by default here: https://github.com/saleor/saleor/blob/9d3d14aacf32660a925d2412cf1fd4a8b07dd17b/saleor/core/utils/random_data.py#L975-L983