fix(announcements): set default resolver in tests (#19365)
This sets the default resolver in settings instead of assuming
`settings.SHOP_ANNOUNCEMENT_RESOLVER_IMPORT` is always `None` as this can cause
tests to fail with:

```python
@contextmanager
    def use_dummy_announcements(
        settings,
        resolver_func: Callable[[], list[Announcement]] = resolve_dummy_announcements,
    ):
        # [...]
>       assert SiteAppConfig.announcements_resolver is None
E       assert <function resolve_announcements at 0xffd0add33740> is None
E        +  where <function resolve_announcements at 0xffd0add33740> = SiteAppConfig.announcements_resolver
```

This also resolves the comment around `UNSET`[^1] where one planned
implementation is to dynamically set the importance level on the client-side
based on the announcement's type and based on the metadata (`extra`).

[^1]: https://github.com/saleor/saleor/pull/19353#discussion_r3452456261